# Generated by Django 3.2.9 on 2021-12-14 21:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CD_lib',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Название библиотеки')),
            ],
        ),
        migrations.CreateModel(
            name='CD',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Название диска')),
                ('capacity', models.CharField(max_length=50, verbose_name='Ёмкость диска')),
                ('cdLib', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='cd.cd_lib')),
            ],
        ),
    ]
